### ISSUE TITLE
Lat/Long Conversion?

### ISSUE THREAD

**Issue by andyvanee** [attack/rats#1]
Hey - nice work on a nasty problem! I'm just wondering if you've looked into converting these to lat/long so they can be placed on a map? From my research it looks like the exact location can't be converted mathematically due to road allowances and other "Special Sections".

http://en.wikipedia.org/wiki/Dominion_Land_Survey

I suppose a map file would need to be included for lookup?

The use case I'm looking for would be something like the following:

``` ruby
quarter_section = Rats.new("NE 1-2-3 W4")
quarter_section.center.latitude
quarter_section.center.longitude
```

Thoughts?

**Comment by attack** [comment]
I used this library for similar purpose, but I don't think latitude and longitude information belongs in `rats`.
`rats` is more useful to parse and validate LSDs (e.g. NE 1-2-3 W4), or to convert them from one format to another.

Adding centre coordinate support would basically require a file mapping each possible LSD to its centre coordinates (of which there are around 1 million), and loading/processing this file would be pretty slow.  Aside, the benefit of this proposed support is that currently `rats` does not know every possible valid/invalid LSD (at the Quarter Section level), and this mapping would allow this detail of validation.

If you wanted to dig into adding this feature, I would probably merge it in if it didn't hinder performance. Though, I am not sure if there is even a free source of centre coordinates that would allow inclusion in this gem.

The application I used `rats` in took user input (parsed by `rats`), then used a [PostGIS](http://postgis.net/) database to convert the LSD to Polygon of Lat/Long coordinates, from which I could calculate area, the centre (as you requested) or display the LSD on Google Maps.

I used files sold by [AltaLIS](http://www.altalis.com/products/property/ats.html) to populate the PostGIS database.

If you have any more questions, feel free to ask.

**Comment by bfmaclean** [comment]
Hello, I have a website where users can search for projects by selecting a center point on a map and entering a radius (i.e. show me all projects within 50 miles of this point).  Now they want to use LSD to pick that initial point instead of looking for it on the map.  How can I zoom to an LSD or convert it to Lat/Long so I can zoom to the Lat/Long for them ??

Thanks,
Blaise
